/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AberturasRouteImport } from './routes/aberturas'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as AcervoIndexRouteImport } from './routes/acervo/index'
import { Route as AcervoSlugRouteImport } from './routes/acervo/$slug'
import { Route as EpisodiosIndexRouteImport } from './routes/episodios/index'
import { Route as EpisodiosSlugRouteImport } from './routes/episodios/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AberturasRoute = AberturasRouteImport.update({
  id: '/aberturas',
  path: '/aberturas',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const AcervoIndexRoute = AcervoIndexRouteImport.update({
  id: '/acervo/',
  path: '/acervo/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcervoSlugRoute = AcervoSlugRouteImport.update({
  id: '/acervo/$slug',
  path: '/acervo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodiosIndexRoute = EpisodiosIndexRouteImport.update({
  id: '/episodios/',
  path: '/episodios/',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodiosSlugRoute = EpisodiosSlugRouteImport.update({
  id: '/episodios/$slug',
  path: '/episodios/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aberturas': typeof AberturasRoute
  '/rankings': typeof RankingsRoute
  '/acervo/$slug': typeof AcervoSlugRoute
  '/episodios/$slug': typeof EpisodiosSlugRoute
  '/acervo/': typeof AcervoIndexRoute
  '/episodios/': typeof EpisodiosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aberturas': typeof AberturasRoute
  '/rankings': typeof RankingsRoute
  '/acervo/$slug': typeof AcervoSlugRoute
  '/episodios/$slug': typeof EpisodiosSlugRoute
  '/acervo': typeof AcervoIndexRoute
  '/episodios': typeof EpisodiosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aberturas': typeof AberturasRoute
  '/rankings': typeof RankingsRoute
  '/acervo/$slug': typeof AcervoSlugRoute
  '/episodios/$slug': typeof EpisodiosSlugRoute
  '/acervo/': typeof AcervoIndexRoute
  '/episodios/': typeof EpisodiosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aberturas'
    | '/rankings'
    | '/acervo/$slug'
    | '/episodios/$slug'
    | '/acervo/'
    | '/episodios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aberturas'
    | '/rankings'
    | '/acervo/$slug'
    | '/episodios/$slug'
    | '/acervo'
    | '/episodios'
  id:
    | '__root__'
    | '/'
    | '/aberturas'
    | '/rankings'
    | '/acervo/$slug'
    | '/episodios/$slug'
    | '/acervo/'
    | '/episodios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AberturasRoute: typeof AberturasRoute
  RankingsRoute: typeof RankingsRoute
  AcervoSlugRoute: typeof AcervoSlugRoute
  EpisodiosSlugRoute: typeof EpisodiosSlugRoute
  AcervoIndexRoute: typeof AcervoIndexRoute
  EpisodiosIndexRoute: typeof EpisodiosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aberturas': {
      id: '/aberturas'
      path: '/aberturas'
      fullPath: '/aberturas'
      preLoaderRoute: typeof AberturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acervo/': {
      id: '/acervo/'
      path: '/acervo'
      fullPath: '/acervo/'
      preLoaderRoute: typeof AcervoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acervo/$slug': {
      id: '/acervo/$slug'
      path: '/acervo/$slug'
      fullPath: '/acervo/$slug'
      preLoaderRoute: typeof AcervoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episodios/': {
      id: '/episodios/'
      path: '/episodios'
      fullPath: '/episodios/'
      preLoaderRoute: typeof EpisodiosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episodios/$slug': {
      id: '/episodios/$slug'
      path: '/episodios/$slug'
      fullPath: '/episodios/$slug'
      preLoaderRoute: typeof EpisodiosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AberturasRoute: AberturasRoute,
  RankingsRoute: RankingsRoute,
  AcervoSlugRoute: AcervoSlugRoute,
  EpisodiosSlugRoute: EpisodiosSlugRoute,
  AcervoIndexRoute: AcervoIndexRoute,
  EpisodiosIndexRoute: EpisodiosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
